// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0xZDSeyIXv9_NbRFKBPf5CQlHHhtGVY',
    appId: '1:398943855292:web:c7a56e6863f7a0ebd7a6b9',
    messagingSenderId: '398943855292',
    projectId: 'wingtrace-ead16',
    authDomain: 'wingtrace-ead16.firebaseapp.com',
    storageBucket: 'wingtrace-ead16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEiUPIKoe04HCA3N5LyZ1Nc2NdArLiyv4',
    appId: '1:398943855292:android:94c2dd5d7afc29a1d7a6b9',
    messagingSenderId: '398943855292',
    projectId: 'wingtrace-ead16',
    storageBucket: 'wingtrace-ead16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkI4Hia5Q1_wHk5orgkRN6iDDwBnBtZ5U',
    appId: '1:398943855292:ios:36e49a995cc9093ad7a6b9',
    messagingSenderId: '398943855292',
    projectId: 'wingtrace-ead16',
    storageBucket: 'wingtrace-ead16.firebasestorage.app',
    iosBundleId: 'com.example.wingTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkI4Hia5Q1_wHk5orgkRN6iDDwBnBtZ5U',
    appId: '1:398943855292:ios:36e49a995cc9093ad7a6b9',
    messagingSenderId: '398943855292',
    projectId: 'wingtrace-ead16',
    storageBucket: 'wingtrace-ead16.firebasestorage.app',
    iosBundleId: 'com.example.wingTrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD0xZDSeyIXv9_NbRFKBPf5CQlHHhtGVY',
    appId: '1:398943855292:web:39ac33f7f3a13b40d7a6b9',
    messagingSenderId: '398943855292',
    projectId: 'wingtrace-ead16',
    authDomain: 'wingtrace-ead16.firebaseapp.com',
    storageBucket: 'wingtrace-ead16.firebasestorage.app',
  );
}
